/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stamfordub;

/**
 *
 * @author User
 */
public class Contract extends javax.swing.JFrame {

    /**
     * Creates new form Contract
     */
    public Contract() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HCareer = new javax.swing.JButton();
        HIQAC = new javax.swing.JButton();
        HLibrary = new javax.swing.JButton();
        HDegreeVarification = new javax.swing.JButton();
        HAboutUs = new javax.swing.JComboBox<>();
        HAdmission = new javax.swing.JComboBox<>();
        HAcademic = new javax.swing.JComboBox<>();
        HStudentForums = new javax.swing.JComboBox<>();
        SignUpBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 10, 80, 23);

        jButton2.setText("Sign In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 10, 80, 23);

        jButton3.setText("Email");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(550, 10, 80, 23);

        jButton4.setText("Contract");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(280, 10, 80, 23);

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stamford Univarsity Bangladesh");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 50, 440, 40);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("LilyUPC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Education for tomorrows world a greener world");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 241, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 630, 40);

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(null);
        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tel : 58155834, 58151469, 58156122,9124161");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(60, 170, 340, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("(Office time: 9 am to 6 pm. Friday Closed.) ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(80, 150, 300, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mobile: 01713082402, 01675694482 ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(90, 130, 270, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dhaka-1209, Bangladesh ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(140, 110, 180, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("744, Satmosjid Road, Dhanmondi ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(110, 90, 240, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/contract.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 310);

        jTabbedPane1.addTab("Head Office", jPanel3);

        jPanel7.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("51, Siddeswari Road,");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(160, 90, 150, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dhaka-1217, Bangladesh ");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(140, 110, 177, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mobile: 01738879598, 01836976941 ");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(110, 130, 263, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" (Office time: 9 am to 6 pm. Friday Closed.) ");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(80, 150, 298, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tel : 58315626, 58315513, 9336932, 9336981, 9355967");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(30, 170, 400, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/contract3.jpg"))); // NOI18N
        jPanel7.add(jLabel4);
        jLabel4.setBounds(0, -20, 470, 330);

        jTabbedPane1.addTab("Siddeswari Campus", jPanel7);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 480, 340);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(160, 140, 480, 340);

        HCareer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HCareer.setText("Career");
        HCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCareerActionPerformed(evt);
            }
        });
        jPanel1.add(HCareer);
        HCareer.setBounds(10, 270, 140, 25);

        HIQAC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HIQAC.setText("IQAC");
        HIQAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIQACActionPerformed(evt);
            }
        });
        jPanel1.add(HIQAC);
        HIQAC.setBounds(10, 310, 140, 25);

        HLibrary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HLibrary.setText("Library");
        HLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(HLibrary);
        HLibrary.setBounds(10, 350, 140, 25);

        HDegreeVarification.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HDegreeVarification.setText("Degree Varification");
        jPanel1.add(HDegreeVarification);
        HDegreeVarification.setBounds(10, 430, 140, 25);

        HAboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAboutUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "About Us", "University Profile", "Board of Trustees", "Management Team", "Employees'(Service) Manual" }));
        jPanel1.add(HAboutUs);
        HAboutUs.setBounds(10, 150, 140, 25);

        HAdmission.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAdmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admission", "Program Information", "Requirements", "Admission Test,", "Admission Schedule", "Apply Online", "Admission Test Result", "Contact to Admission" }));
        jPanel1.add(HAdmission);
        HAdmission.setBounds(10, 190, 140, 25);

        HAcademic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAcademic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Team of Faculty", "Academic Excellence", "Academic Calender", "Academic Policy", "Facilities for Student", "Credit Transfer", "Job Placement", "Clall For Paper", "Schedule", "Certificate Requirements", "Academic Result" }));
        jPanel1.add(HAcademic);
        HAcademic.setBounds(10, 230, 140, 25);

        HStudentForums.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HStudentForums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Forums", "Career Counseling and Placement Centre", "Stamford University Volunteers", "Public Relations Division (PRD)", "STRAYBIRD,Stamford University Math_Circle", "Stamford Debate Forum,Stamford Institute on Addiction And Rehabilitation (SIAR)", "Center for Professional Development in Business (CPDB)", "Stamford University Research Center (SURC)", "Japanese Language Center,International Center for Development & Research", "Center for South Asian Policy Research", "Center of Continuing Education", "Consultancy & Research (CECR)" }));
        jPanel1.add(HStudentForums);
        HStudentForums.setBounds(10, 390, 140, 25);

        SignUpBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/BackIcon.PNG"))); // NOI18N
        SignUpBack.setText("Back to Main");
        SignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBackActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBack);
        SignUpBack.setBounds(20, 10, 120, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/contract2.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentSignUp hsignup = new StudentSignUp();
        this.dispose();
        hsignup.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void HCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HCareerActionPerformed

    private void HIQACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIQACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIQACActionPerformed

    private void HLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HLibraryActionPerformed

    private void SignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBackActionPerformed
        // TODO add your handling code here:
        MainPage mainpage = new MainPage();
        this.dispose();
        mainpage.setVisible(true);
    }//GEN-LAST:event_SignUpBackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignIn hsignin = new SignIn();
        this.dispose();
        hsignin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Email email = new Email();
        this.dispose();
        email.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contract.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contract().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HAboutUs;
    private javax.swing.JComboBox<String> HAcademic;
    private javax.swing.JComboBox<String> HAdmission;
    private javax.swing.JButton HCareer;
    private javax.swing.JButton HDegreeVarification;
    private javax.swing.JButton HIQAC;
    private javax.swing.JButton HLibrary;
    private javax.swing.JComboBox<String> HStudentForums;
    private javax.swing.JButton SignUpBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
