/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stamfordub;

/**
 *
 * @author User
 */
public class Email extends javax.swing.JFrame {

    /**
     * Creates new form Email
     */
    public Email() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HCareer = new javax.swing.JButton();
        HIQAC = new javax.swing.JButton();
        HLibrary = new javax.swing.JButton();
        HDegreeVarification = new javax.swing.JButton();
        HAboutUs = new javax.swing.JComboBox<>();
        HAdmission = new javax.swing.JComboBox<>();
        HAcademic = new javax.swing.JComboBox<>();
        HStudentForums = new javax.swing.JComboBox<>();
        SignUpBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 10, 80, 23);

        jButton2.setText("Sign In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 10, 80, 23);

        jButton3.setText("Email");
        jPanel1.add(jButton3);
        jButton3.setBounds(550, 10, 80, 23);

        jButton4.setText("Contract");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(280, 10, 80, 23);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("LilyUPC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Education for tomorrows world a greener world");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(241, 0, 389, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 630, 40);

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(null);
        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(220, 0, 60, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 480, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Gmail mail.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(200, 70, 90, 80);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Zoho mail.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(80, 70, 90, 80);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/aol mail.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(320, 70, 90, 80);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Outlook mail.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(80, 180, 90, 80);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/yandex mail.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);
        jButton10.setBounds(200, 180, 90, 80);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Icloude mail.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(320, 180, 90, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Email2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 490, 340);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/StaUB.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(-140, 290, 630, 44);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(160, 140, 480, 340);

        HCareer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HCareer.setText("Career");
        HCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCareerActionPerformed(evt);
            }
        });
        jPanel1.add(HCareer);
        HCareer.setBounds(10, 270, 140, 25);

        HIQAC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HIQAC.setText("IQAC");
        HIQAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIQACActionPerformed(evt);
            }
        });
        jPanel1.add(HIQAC);
        HIQAC.setBounds(10, 310, 140, 25);

        HLibrary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HLibrary.setText("Library");
        HLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(HLibrary);
        HLibrary.setBounds(10, 350, 140, 25);

        HDegreeVarification.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HDegreeVarification.setText("Degree Varification");
        jPanel1.add(HDegreeVarification);
        HDegreeVarification.setBounds(10, 430, 140, 25);

        HAboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAboutUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "About Us", "University Profile", "Board of Trustees", "Management Team", "Employees'(Service) Manual" }));
        jPanel1.add(HAboutUs);
        HAboutUs.setBounds(10, 150, 140, 25);

        HAdmission.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAdmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admission", "Program Information", "Requirements", "Admission Test,", "Admission Schedule", "Apply Online", "Admission Test Result", "Contact to Admission" }));
        jPanel1.add(HAdmission);
        HAdmission.setBounds(10, 190, 140, 25);

        HAcademic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAcademic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Team of Faculty", "Academic Excellence", "Academic Calender", "Academic Policy", "Facilities for Student", "Credit Transfer", "Job Placement", "Clall For Paper", "Schedule", "Certificate Requirements", "Academic Result" }));
        jPanel1.add(HAcademic);
        HAcademic.setBounds(10, 230, 140, 25);

        HStudentForums.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HStudentForums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Forums", "Career Counseling and Placement Centre", "Stamford University Volunteers", "Public Relations Division (PRD)", "STRAYBIRD,Stamford University Math_Circle", "Stamford Debate Forum,Stamford Institute on Addiction And Rehabilitation (SIAR)", "Center for Professional Development in Business (CPDB)", "Stamford University Research Center (SURC)", "Japanese Language Center,International Center for Development & Research", "Center for South Asian Policy Research", "Center of Continuing Education", "Consultancy & Research (CECR)" }));
        jPanel1.add(HStudentForums);
        HStudentForums.setBounds(10, 390, 140, 25);

        SignUpBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/BackIcon.PNG"))); // NOI18N
        SignUpBack.setText("Back to main");
        SignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBackActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBack);
        SignUpBack.setBounds(20, 10, 120, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/StaUB.gif"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 50, 650, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/Email.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentSignUp hsignup = new StudentSignUp();
        this.dispose();
        hsignup.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Contract contract = new Contract();
        this.dispose();
        contract.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void HCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HCareerActionPerformed

    private void HIQACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIQACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIQACActionPerformed

    private void HLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HLibraryActionPerformed

    private void SignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBackActionPerformed
        // TODO add your handling code here:
        MainPage mainpage = new MainPage();
        this.dispose();
        mainpage.setVisible(true);
    }//GEN-LAST:event_SignUpBackActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignIn hsignin = new SignIn();
        this.dispose();
        hsignin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HAboutUs;
    private javax.swing.JComboBox<String> HAcademic;
    private javax.swing.JComboBox<String> HAdmission;
    private javax.swing.JButton HCareer;
    private javax.swing.JButton HDegreeVarification;
    private javax.swing.JButton HIQAC;
    private javax.swing.JButton HLibrary;
    private javax.swing.JComboBox<String> HStudentForums;
    private javax.swing.JButton SignUpBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
