
package stamfordub;
import java.sql.*;
import java.util.Arrays;
import javax.swing.*;

public class SignIn extends javax.swing.JFrame {

    
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        HCareer = new javax.swing.JButton();
        HIQAC = new javax.swing.JButton();
        HLibrary = new javax.swing.JButton();
        HDegreeVarification = new javax.swing.JButton();
        HAboutUs = new javax.swing.JComboBox<>();
        HAdmission = new javax.swing.JComboBox<>();
        HAcademic = new javax.swing.JComboBox<>();
        HStudentForums = new javax.swing.JComboBox<>();
        SignUpBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 10, 80, 23);

        jButton2.setText("Sign In");
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 10, 80, 23);

        jButton3.setText("Email");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(550, 10, 80, 23);

        jButton4.setText("Contract");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(280, 10, 80, 23);

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stamford Univarsity Bangladesh");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 50, 450, 40);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("LilyUPC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Education for tomorrows world a greener world");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 241, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 630, 40);

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(null);
        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID  :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(60, 130, 90, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password  :");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(60, 170, 90, 17);

        StudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDActionPerformed(evt);
            }
        });
        jPanel4.add(StudentID);
        StudentID.setBounds(160, 130, 170, 25);
        jPanel4.add(Password);
        Password.setBounds(160, 170, 170, 25);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setText("Sign In");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(250, 220, 79, 25);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setText("Forgate Your Password");
        jPanel4.add(jButton14);
        jButton14.setBounds(70, 220, 170, 25);

        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/SignIn.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(2, -18, 470, 330);

        jTabbedPane1.addTab("Sign In Student Account", jPanel3);

        jPanel7.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/SignIn2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(0, -20, 480, 850);

        jTabbedPane1.addTab("Sign In Teacher Account", jPanel7);

        jPanel8.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/SignIn4.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(0, -20, 480, 330);

        jTabbedPane1.addTab("Sign In Employee Account", jPanel8);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 480, 340);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(160, 140, 480, 340);

        HCareer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HCareer.setText("Career");
        HCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HCareerActionPerformed(evt);
            }
        });
        jPanel1.add(HCareer);
        HCareer.setBounds(10, 270, 140, 25);

        HIQAC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HIQAC.setText("IQAC");
        HIQAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIQACActionPerformed(evt);
            }
        });
        jPanel1.add(HIQAC);
        HIQAC.setBounds(10, 310, 140, 25);

        HLibrary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HLibrary.setText("Library");
        HLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(HLibrary);
        HLibrary.setBounds(10, 350, 140, 25);

        HDegreeVarification.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HDegreeVarification.setText("Degree Varification");
        jPanel1.add(HDegreeVarification);
        HDegreeVarification.setBounds(10, 430, 140, 25);

        HAboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAboutUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "About Us", "University Profile", "Board of Trustees", "Management Team", "Employees'(Service) Manual" }));
        jPanel1.add(HAboutUs);
        HAboutUs.setBounds(10, 150, 140, 25);

        HAdmission.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAdmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admission", "Program Information", "Requirements", "Admission Test,", "Admission Schedule", "Apply Online", "Admission Test Result", "Contact to Admission" }));
        jPanel1.add(HAdmission);
        HAdmission.setBounds(10, 190, 140, 25);

        HAcademic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HAcademic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Team of Faculty", "Academic Excellence", "Academic Calender", "Academic Policy", "Facilities for Student", "Credit Transfer", "Job Placement", "Clall For Paper", "Schedule", "Certificate Requirements", "Academic Result" }));
        jPanel1.add(HAcademic);
        HAcademic.setBounds(10, 230, 140, 25);

        HStudentForums.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HStudentForums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Forums", "Career Counseling and Placement Centre", "Stamford University Volunteers", "Public Relations Division (PRD)", "STRAYBIRD,Stamford University Math_Circle", "Stamford Debate Forum,Stamford Institute on Addiction And Rehabilitation (SIAR)", "Center for Professional Development in Business (CPDB)", "Stamford University Research Center (SURC)", "Japanese Language Center,International Center for Development & Research", "Center for South Asian Policy Research", "Center of Continuing Education", "Consultancy & Research (CECR)" }));
        jPanel1.add(HStudentForums);
        HStudentForums.setBounds(10, 390, 140, 25);

        SignUpBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/BackIcon.PNG"))); // NOI18N
        SignUpBack.setText("Back to Main");
        SignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBackActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBack);
        SignUpBack.setBounds(20, 10, 120, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/SignIn3.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 650, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentSignUp hsignup = new StudentSignUp();
        this.dispose();
        hsignup.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Contract contract = new Contract();
        this.dispose();
        contract.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
        String url = "jdbc:sqlserver://localhost:1433;databaseName=JavaProject";
        String username = "JackNayem";
        String password = "asdfghjkl";       
       Connection con = DriverManager.getConnection(url, username, password);
       String Query ="select * from SignUpStudent where StdID=? and Pass=?";
       PreparedStatement pst = con.prepareStatement(Query);
       pst.setString(1, StudentID.getText());
       pst.setString(2, Arrays.toString(Password.getPassword()));
       

       
       // PreparedStatement stmt = con.createStatement(Query);
        //String Query = "insert into SignUpStudent (StdID,BirthDate,Trimester,EmailAddress,MobileNumber,Pass,passReturn) values ('"+StudentID.getText()+"','"+BirthDate.getSelectedDate()+"','"+Trimester.getSelectedItem()+"','"+EmailID.getText()+"','"+PhoneNumber.getText()+"','"+Arrays.toString(Password.getPassword())+"','"+Arrays.toString(ReenterPassword.getPassword())+"')";
       // String Query = "Select * from SingIn where StudentID='"+StudentID.getText()+"' and Password='"+Arrays.toString(Password.getPassword())+"'";
       // boolean rs =stmt.execute(Query);
           
           ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Match");
                StudentProfile stdprofile = new StudentProfile();
                this.dispose();
                stdprofile.setVisible(true);
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Not Match");
                StudentID.setText("");
                Password.setText("");
                
            }
            
            
        
       
       }catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,ex.toString());
       }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void HCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HCareerActionPerformed

    private void HIQACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIQACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIQACActionPerformed

    private void HLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HLibraryActionPerformed

    private void SignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBackActionPerformed
        // TODO add your handling code here:
        MainPage mainpage = new MainPage();
        this.dispose();
        mainpage.setVisible(true);
    }//GEN-LAST:event_SignUpBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Email email = new Email();
        this.dispose();
        email.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HAboutUs;
    private javax.swing.JComboBox<String> HAcademic;
    private javax.swing.JComboBox<String> HAdmission;
    private javax.swing.JButton HCareer;
    private javax.swing.JButton HDegreeVarification;
    private javax.swing.JButton HIQAC;
    private javax.swing.JButton HLibrary;
    private javax.swing.JComboBox<String> HStudentForums;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SignUpBack;
    private javax.swing.JTextField StudentID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
