/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stamfordub;

/**
 *
 * @author User
 */
public class StudentProfile extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton16 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        SUCareer = new javax.swing.JButton();
        SUIQAC = new javax.swing.JButton();
        SULibrary = new javax.swing.JButton();
        SUDegreeVarification = new javax.swing.JButton();
        SUAboutUs = new javax.swing.JComboBox<>();
        SUAdmission = new javax.swing.JComboBox<>();
        SUAcademic = new javax.swing.JComboBox<>();
        SUStudentForums = new javax.swing.JComboBox<>();
        SignUpBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(113, 201, 241));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(370, 10, 80, 23);

        jButton2.setBackground(new java.awt.Color(113, 201, 241));
        jButton2.setText("Sign In");
        jPanel2.add(jButton2);
        jButton2.setBounds(460, 10, 80, 23);

        jButton3.setBackground(new java.awt.Color(113, 201, 241));
        jButton3.setText("Email");
        jPanel2.add(jButton3);
        jButton3.setBounds(550, 10, 80, 23);

        jButton4.setBackground(new java.awt.Color(113, 201, 241));
        jButton4.setText("Contract");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(280, 10, 80, 23);

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 40)); // NOI18N
        jLabel1.setText("Welcome to Stamford Univarsity Bangladesh");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 610, 40);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("LilyUPC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Education for tomorrows world a greener world");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 241, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 90, 630, 40);

        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(null);
        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 0, 0);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Welcome to SUB online Service");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 230, 30);

        jButton13.setText("Log Out");
        jPanel1.add(jButton13);
        jButton13.setBounds(400, 2, 79, 23);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 30);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(10, 60, 80, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Computer Science & Engineering");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(100, 80, 190, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Batch No 58");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(100, 100, 90, 10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Section A");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(100, 120, 60, 10);

        jButton15.setText("Message");
        jPanel4.add(jButton15);
        jButton15.setBounds(10, 160, 75, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(110, 160, 360, 70);

        jButton16.setText("Post");
        jPanel4.add(jButton16);
        jButton16.setBounds(410, 240, 53, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Jack Nayem");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(100, 60, 90, 17);

        jButton5.setText("Profile");
        jPanel4.add(jButton5);
        jButton5.setBounds(0, 30, 90, 25);

        jButton6.setText("TimeLine");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(90, 30, 90, 25);

        jButton8.setText("My Result");
        jPanel4.add(jButton8);
        jButton8.setBounds(280, 30, 90, 25);

        jButton9.setText("My Payment");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(180, 30, 100, 25);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My Library", "Book in Hand", "Book Circulation" }));
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(370, 30, 80, 25);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(160, 140, 480, 360);

        SUCareer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUCareer.setText("Career");
        SUCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUCareerActionPerformed(evt);
            }
        });
        jPanel2.add(SUCareer);
        SUCareer.setBounds(10, 270, 140, 25);

        SUIQAC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUIQAC.setText("IQAC");
        SUIQAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUIQACActionPerformed(evt);
            }
        });
        jPanel2.add(SUIQAC);
        SUIQAC.setBounds(10, 310, 140, 25);

        SULibrary.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SULibrary.setText("Library");
        SULibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SULibraryActionPerformed(evt);
            }
        });
        jPanel2.add(SULibrary);
        SULibrary.setBounds(10, 350, 140, 25);

        SUDegreeVarification.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUDegreeVarification.setText("Degree Varification");
        jPanel2.add(SUDegreeVarification);
        SUDegreeVarification.setBounds(10, 430, 140, 23);

        SUAboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUAboutUs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "About Us", "University Profile", "Board of Trustees", "Management Team", "Employees'(Service) Manual" }));
        jPanel2.add(SUAboutUs);
        SUAboutUs.setBounds(10, 150, 140, 25);

        SUAdmission.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUAdmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admission", "Program Information", "Requirements", "Admission Test,", "Admission Schedule", "Apply Online", "Admission Test Result", "Contact to Admission" }));
        jPanel2.add(SUAdmission);
        SUAdmission.setBounds(10, 190, 140, 25);

        SUAcademic.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUAcademic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academic", "Team of Faculty", "Academic Excellence", "Academic Calender", "Academic Policy", "Facilities for Student", "Credit Transfer", "Job Placement", "Clall For Paper", "Schedule", "Certificate Requirements", "Academic Result" }));
        jPanel2.add(SUAcademic);
        SUAcademic.setBounds(10, 230, 140, 25);

        SUStudentForums.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SUStudentForums.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student Forums", "Career Counseling and Placement Centre", "Stamford University Volunteers", "Public Relations Division (PRD)", "STRAYBIRD,Stamford University Math_Circle", "Stamford Debate Forum,Stamford Institute on Addiction And Rehabilitation (SIAR)", "Center for Professional Development in Business (CPDB)", "Stamford University Research Center (SURC)", "Japanese Language Center,International Center for Development & Research", "Center for South Asian Policy Research", "Center of Continuing Education", "Consultancy & Research (CECR)" }));
        jPanel2.add(SUStudentForums);
        SUStudentForums.setBounds(10, 390, 140, 25);

        SignUpBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stamfordub/BackIcon.PNG"))); // NOI18N
        SignUpBack.setText("Back to  Main");
        SignUpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBackActionPerformed(evt);
            }
        });
        jPanel2.add(SignUpBack);
        SignUpBack.setBounds(20, 10, 120, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SUCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUCareerActionPerformed

    private void SUIQACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUIQACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUIQACActionPerformed

    private void SULibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SULibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SULibraryActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void SignUpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBackActionPerformed
        // TODO add your handling code here:
        MainPage mainpage = new MainPage();
        this.dispose();
        mainpage.setVisible(true);
    }//GEN-LAST:event_SignUpBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SUAboutUs;
    private javax.swing.JComboBox<String> SUAcademic;
    private javax.swing.JComboBox<String> SUAdmission;
    private javax.swing.JButton SUCareer;
    private javax.swing.JButton SUDegreeVarification;
    private javax.swing.JButton SUIQAC;
    private javax.swing.JButton SULibrary;
    private javax.swing.JComboBox<String> SUStudentForums;
    private javax.swing.JButton SignUpBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
